---
- name: Install Docker, Docker Compose, and Nginx
  hosts: localhost
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

  roles:
    - role: docker
    - role: docker-compose
    - role: nginx
